# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-21 22:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20160221_2112'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='relationship',
            unique_together=set([]),
        ),
    ]
